version: "3.5"
services:

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  db-local:
    image: postgres:14
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

  api:
    image: ghcr.io/strelka-skaut/api:a24f2740
    ports:
      - "2001:2000"

  proxy:
    image: envoyproxy/envoy:v1.21-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "80:8080"

  file-server:
    image: nginx
    volumes:
      - ./data:/usr/share/nginx/html
    ports:
      - "9000:80"
