version: "3.8"
services:

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    ports:
      - "2000:2000"

  proxy:
    image: envoyproxy/envoy:v1.21-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "80:8080"
