version: "3.5"
services:

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  file-server:
    image: nginx
    volumes:
      - ./data:/usr/share/nginx/html
    ports:
      - "9000:80"

  api:
    build:
      context: .

  proxy:
    image: envoyproxy/envoy:v1.21-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "80:8080"
