name: .NET

on: [ push ]

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - run: dotnet new nugetconfig
      - run: ls -lah
      - run: dotnet nuget add source --configfile nuget.config --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/strelka-skaut/index.json"
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
      - run: |
          SHORT_COMMIT_SHA="$(echo "${{ github.sha }}" | cut -c -8)"
          IMAGE_NAME="ghcr.io/${{ github.repository }}"
          
          docker build -t "$IMAGE_NAME:$SHORT_COMMIT_SHA" -f Dockerfile .
          docker push "$IMAGE_NAME:$SHORT_COMMIT_SHA"
          docker tag "$IMAGE_NAME:$SHORT_COMMIT_SHA" "$IMAGE_NAME:latest"
