name: .NET

on: [ push ]

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - run: dotnet new nugetconfig
      - run: dotnet nuget add source \
          --configfile nuget.config
          --username "${{ github.actor }}" \
          --password "${{ secrets.GITHUB_TOKEN }}" \
          --store-password-in-clear-text \
          --name github \
          "https://nuget.pkg.github.com/strelka-skaut/index.json"
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
      - run: |
          IMAGE_TAG="$(echo "${{ github.sha }}" | cut -c -8)"
          IMAGE_NAME="ghcr.io/${{ github.repository }}:$IMAGE_TAG"
          
          docker build -t "$IMAGE_NAME" -f Dockerfile .
          docker push "$IMAGE_NAME"
