name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET.
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      
      - name: Add GitHub Packages Nuget source.
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/strelka-skaut/index.json"

      - name: Restore dependencies.
        run: dotnet restore

      - name: Build.
        run: dotnet build --no-restore

#      - name: Test
#        run: dotnet test --no-build --verbosity normal

  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Login to Container Registry.
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io

          IMAGE_TAG="$(echo "${{ github.sha }}" | cut -c -8)"
          IMAGE_NAME="ghcr.io/${{ github.repository }}:$IMAGE_TAG"

          docker build -t "$IMAGE_NAME" -f Dockerfile .
          docker push "$IMAGE_NAME"
